[program:data-download]
priority=30
directory=/app/Modules
command=bash -c "sleep 10; python3 /app/Modules/DataAutoDownload.py"
autostart=true
autorestart=unexpected
startsecs=1
startretries=0
stopasgroup=true
killasgroup=true

redirect_stderr=true
stdout_logfile=/var/log/supervisor/data-download-stdout.log
stderr_logfile=/var/log/supervisor/data-download-stderr.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
stdout_logfile_backups=5
stderr_logfile_backups=5
